#!/usr/bin/env python3
// Connect to MongoDB and list all databases
const databases = db.adminCommand('listDatabases').databases;
databases.forEach(database => {
    print(database.name + "\t" + (database.sizeOnDisk / (1024 * 1024)).toFixed(2) + " MB");
});

quit();
